In [1]:
%matplotlib inline 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from scipy.stats import zscore
import seaborn as sns

In [2]:
NNH = KNeighborsClassifier(n_neighbors= 5 , weights = 'distance' )

In [3]:
Dataset_final_df = pd.read_csv("Dataset_final.csv")

In [4]:
Dataset_final_df.columns

Index(['ImgID', 'BodySize', 'Complexion', 'Occasion', 'DressColor',
       'DressDesign', 'Matching'],
      dtype='object')

In [5]:
Dataset_final_df.shape

(355, 7)

In [6]:
Dataset_final_df.dtypes

ImgID          object
BodySize       object
Complexion     object
Occasion       object
DressColor     object
DressDesign    object
Matching       object
dtype: object

In [7]:
Dataset_final_df['Matching'].value_counts()

Y    229
N    126
Name: Matching, dtype: int64

In [8]:
Dataset_final_df = Dataset_final_df.drop(labels = "ImgID", axis = 1)

In [9]:
Dataset_final_df['BodySize'] =Dataset_final_df.BodySize.astype('category')
Dataset_final_df['Complexion'] = Dataset_final_df.Complexion.astype('category')
Dataset_final_df['Occasion'] = Dataset_final_df.Occasion.astype('category')
Dataset_final_df['DressColor'] = Dataset_final_df.DressColor.astype('category')
Dataset_final_df['DressDesign'] = Dataset_final_df.DressDesign.astype('category')
Dataset_final_df['Matching'] = Dataset_final_df.Matching.astype('category')
Dataset_final_df.dtypes

BodySize       category
Complexion     category
Occasion       category
DressColor     category
DressDesign    category
Matching       category
dtype: object

In [10]:
Dataset_final_df.describe().transpose()

            count unique          top freq
BodySize      355      6           XL  154
Complexion    355      6         Fair   94
Occasion      355      8       Casual  141
DressColor    355     75        Black   45
DressDesign   355     27  Linen Shirt   69
Matching      355      2            Y  229

In [11]:
Dataset_final_df.groupby(["Matching"]).count()

          BodySize  Complexion  Occasion  DressColor  DressDesign
Matching
N              126         126       126         126          126
Y              229         229       229         229          229

In [12]:
Dataset_final_df = Dataset_final_df.drop(labels = "Matching", axis = 1)

In [13]:
Dataset_final_df.shape

(355, 5)

In [14]:
Dataset_final_df=pd.get_dummies(Dataset_final_df)
Dataset_final_df

,BodySize_L,BodySize_M,BodySize_S,BodySize_XL,BodySize_XS,BodySize_XXL,Complexion_Brown,Complexion_Dark Brown,Complexion_Fair,Complexion_Medium,...,DressDesign_Kurti,DressDesign_Linen Shirt,DressDesign_Overshirt,DressDesign_Oxford Button-Down Shirt,DressDesign_Polo Shirt,DressDesign_Round Neck,DressDesign_Sflannel Shirt,DressDesign_Sport jacket,DressDesign_T Shirt,DressDesign_Winter Wear
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
353,0,0,0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
354,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
Dataset_final_df_dummy=pd.get_dummies(Dataset_final_df,drop_first=True)
Dataset_final_df_dummy

,BodySize_L,BodySize_M,BodySize_S,BodySize_XL,BodySize_XS,BodySize_XXL,Complexion_Brown,Complexion_Dark Brown,Complexion_Fair,Complexion_Medium,...,DressDesign_Kurti,DressDesign_Linen Shirt,DressDesign_Overshirt,DressDesign_Oxford Button-Down Shirt,DressDesign_Polo Shirt,DressDesign_Round Neck,DressDesign_Sflannel Shirt,DressDesign_Sport jacket,DressDesign_T Shirt,DressDesign_Winter Wear
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
351,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
353,0,0,0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
354,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
X = np.array(Dataset_final_df)
X

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [17]:
y = np.array(Dataset_final_df)
y

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [18]:
array=Dataset_final_df.values
x=array[:,0:5]
y=array[:,5]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [20]:
X_train.shape

(248, 122)

In [21]:
X_test.shape

(107, 122)

In [22]:
NNH.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [23]:
predicted_labels = NNH.predict(X_test)
NNH.score(X_test, y_test)

0.9626168224299065